
paypal:
  client-id: ASDlfS_0Sc2AWVcH_aQz1PP8RiPxddnKRo2VCJ1xDpHJU67FcANBT15ju9lqXayNehFVT17tcTfd-50a
  client-secret: ENOkbFDqeADIsmz_i_-en1eBEHWKmfZZsPdoDPeyP_uAiC30IgY2aoNwYdVGy1XC6GVSMuwFnJf-av-D
  mode: sandbox
